name: Unit Testing, Coverage Collection, Package, Release, Documentation and Publish

on: 
  push:
  workflow_dispatch:

jobs:

  Params:
    uses: pyTooling/Actions/.github/workflows/Params.yml@dev
    with:
      name: pyEDAA.ProjectModel
      python_version_list: '3.7 3.8 3.9 3.10'

  UnitTesting:
    uses: pyTooling/Actions/.github/workflows/UnitTesting.yml@dev
    needs:
      - Params
    with:
      jobs: ${{ needs.Params.outputs.python_jobs }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}

  Coverage:
    uses: pyTooling/Actions/.github/workflows/CoverageCollection.yml@dev
    needs:
      - Params
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
    secrets:
      codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  StaticTypeCheck:
    uses: pyTooling/Actions/.github/workflows/StaticTypeCheck.yml@dev
    needs:
      - Params
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      commands: |
        cd pyEDAA
        mypy --html-report ../htmlmypy -p ProjectModel
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.typing }}

  Release:
    uses: pyTooling/Actions/.github/workflows/Release.yml@dev
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - UnitTesting
      - Coverage
      - StaticTypeCheck

  Package:
    uses: pyTooling/Actions/.github/workflows/Package.yml@dev
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - Params
      - Coverage
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}

  PublishOnPyPI:
    uses: pyTooling/Actions/.github/workflows/PublishOnPyPI.yml@dev
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - Params
      - Release
      - Package
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  VerifyDocs:
    uses: pyTooling/Actions/.github/workflows/VerifyDocs.yml@dev
    needs:
      - Params
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}

  BuildTheDocs:
    uses: pyTooling/Actions/.github/workflows/BuildTheDocs.yml@dev
    needs:
      - Params
      - VerifyDocs
    with:
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}

  PublishToGitHubPages:
    uses: pyTooling/Actions/.github/workflows/PublishToGitHubPages.yml@dev
    needs:
      - Params
      - BuildTheDocs
      - Coverage
      - StaticTypeCheck
    with:
      doc: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
      coverage: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
      typing: ${{ fromJson(needs.Params.outputs.params).artifacts.typing }}


  ArtifactCleanUp:
    name: üóëÔ∏è Artifact Cleanup
    runs-on: ubuntu-latest
    needs:
      - Params
      - Coverage
      - StaticTypeCheck
      - BuildTheDocs
      - PublishToGitHubPages

    steps:

      - name: üóëÔ∏è Delete package Artifacts
        if: ${{ ! startsWith(github.ref, 'refs/tags') }}
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            ${{ fromJson(needs.Params.outputs.params).artifacts.package }}

      - name: üóëÔ∏è Delete all Artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-*
            ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
            ${{ fromJson(needs.Params.outputs.params).artifacts.typing }}
            ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
